openapi: 3.0.3
info:
  title: Product Catalog API
  description: API for managing products, categories, and product variations
  version: 1.0.0
  contact:
    name: National Clothing Store
    email: api@nationalclothingstore.com

paths:
  /api/v1/categories:
    get:
      summary: Get all categories
      tags:
        - Categories
      parameters:
        - name: includeInactive
          in: query
          schema:
            type: boolean
            default: false
        - name: parentId
          in: query
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: List of categories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/ServerError'

    post:
      summary: Create new category
      tags:
        - Categories
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCategoryRequest'
      responses:
        '201':
          description: Category created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/ServerError'

  /api/v1/categories/{id}:
    get:
      summary: Get category by ID
      tags:
        - Categories
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Category details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '404':
          $ref: '#/components/responses/NotFound'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/ServerError'

    put:
      summary: Update category
      tags:
        - Categories
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCategoryRequest'
      responses:
        '200':
          description: Category updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/ServerError'

    delete:
      summary: Delete category
      tags:
        - Categories
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Category deleted successfully
        '404':
          $ref: '#/components/responses/NotFound'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/ServerError'

  /api/v1/products:
    get:
      summary: Get products with filtering and pagination
      tags:
        - Products
      parameters:
        - name: categoryId
          in: query
          schema:
            type: string
            format: uuid
        - name: search
          in: query
          schema:
            type: string
        - name: page
          in: query
          schema:
            type: integer
            default: 1
            minimum: 1
        - name: pageSize
          in: query
          schema:
            type: integer
            default: 20
            minimum: 1
            maximum: 100
        - name: sortBy
          in: query
          schema:
            type: string
            enum: [name, price, createdAt]
            default: createdAt
        - name: sortOrder
          in: query
          schema:
            type: string
            enum: [asc, desc]
            default: desc
      responses:
        '200':
          description: Paginated list of products
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedProductResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/ServerError'

    post:
      summary: Create new product
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProductRequest'
      responses:
        '201':
          description: Product created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/ServerError'

  /api/v1/products/{id}:
    get:
      summary: Get product by ID
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Product details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          $ref: '#/components/responses/NotFound'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/ServerError'

    put:
      summary: Update product
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProductRequest'
      responses:
        '200':
          description: Product updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/ServerError'

  /api/v1/products/{id}/variations:
    get:
      summary: Get product variations
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: List of product variations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductVariation'
        '404':
          $ref: '#/components/responses/NotFound'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/ServerError'

    post:
      summary: Add product variation
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProductVariationRequest'
      responses:
        '201':
          description: Product variation created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductVariation'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/ServerError'

components:
  schemas:
    Category:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          minLength: 1
          maxLength: 100
        description:
          type: string
          maxLength: 500
        code:
          type: string
          minLength: 1
          maxLength: 20
        parentCategoryId:
          type: string
          format: uuid
          nullable: true
        sortOrder:
          type: integer
          minimum: 0
        isActive:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    CreateCategoryRequest:
      type: object
      required:
        - name
        - code
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
        description:
          type: string
          maxLength: 500
        code:
          type: string
          minLength: 1
          maxLength: 20
        parentCategoryId:
          type: string
          format: uuid
          nullable: true
        sortOrder:
          type: integer
          minimum: 0
          default: 0

    UpdateCategoryRequest:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
        description:
          type: string
          maxLength: 500
        code:
          type: string
          minLength: 1
          maxLength: 20
        parentCategoryId:
          type: string
          format: uuid
          nullable: true
        sortOrder:
          type: integer
          minimum: 0
        isActive:
          type: boolean

    Product:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          minLength: 1
          maxLength: 200
        description:
          type: string
          maxLength: 1000
        sku:
          type: string
          minLength: 1
          maxLength: 50
        barcode:
          type: string
          maxLength: 50
        basePrice:
          type: number
          format: decimal
          minimum: 0
        costPrice:
          type: number
          format: decimal
          minimum: 0
        brand:
          type: string
          maxLength: 100
        season:
          type: string
          maxLength: 50
        collection:
          type: string
          maxLength: 100
        categoryId:
          type: string
          format: uuid
        category:
          $ref: '#/components/schemas/Category'
        isActive:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        variations:
          type: array
          items:
            $ref: '#/components/schemas/ProductVariation'
        images:
          type: array
          items:
            $ref: '#/components/schemas/ProductImage'

    ProductVariation:
      type: object
      properties:
        id:
          type: string
          format: uuid
        size:
          type: string
          maxLength: 20
        color:
          type: string
          maxLength: 50
        sku:
          type: string
          minLength: 1
          maxLength: 50
        barcode:
          type: string
          maxLength: 50
        price:
          type: number
          format: decimal
          minimum: 0
        costPrice:
          type: number
          format: decimal
          minimum: 0
        weight:
          type: integer
          minimum: 0
        isActive:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    ProductImage:
      type: object
      properties:
        id:
          type: string
          format: uuid
        fileName:
          type: string
          maxLength: 255
        filePath:
          type: string
          maxLength: 500
        altText:
          type: string
          maxLength: 255
        sortOrder:
          type: integer
          minimum: 0
        isPrimary:
          type: boolean
        createdAt:
          type: string
          format: date-time

    CreateProductRequest:
      type: object
      required:
        - name
        - sku
        - basePrice
        - costPrice
        - categoryId
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 200
        description:
          type: string
          maxLength: 1000
        sku:
          type: string
          minLength: 1
          maxLength: 50
        barcode:
          type: string
          maxLength: 50
        basePrice:
          type: number
          format: decimal
          minimum: 0
        costPrice:
          type: number
          format: decimal
          minimum: 0
        brand:
          type: string
          maxLength: 100
        season:
          type: string
          maxLength: 50
        collection:
          type: string
          maxLength: 100
        categoryId:
          type: string
          format: uuid

    UpdateProductRequest:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 200
        description:
          type: string
          maxLength: 1000
        barcode:
          type: string
          maxLength: 50
        basePrice:
          type: number
          format: decimal
          minimum: 0
        costPrice:
          type: number
          format: decimal
          minimum: 0
        brand:
          type: string
          maxLength: 100
        season:
          type: string
          maxLength: 50
        collection:
          type: string
          maxLength: 100
        categoryId:
          type: string
          format: uuid
        isActive:
          type: boolean

    CreateProductVariationRequest:
      type: object
      required:
        - size
        - color
        - sku
        - price
        - costPrice
      properties:
        size:
          type: string
          minLength: 1
          maxLength: 20
        color:
          type: string
          minLength: 1
          maxLength: 50
        sku:
          type: string
          minLength: 1
          maxLength: 50
        barcode:
          type: string
          maxLength: 50
        price:
          type: number
          format: decimal
          minimum: 0
        costPrice:
          type: number
          format: decimal
          minimum: 0
        weight:
          type: integer
          minimum: 0

    PagedProductResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Product'
        pagination:
          $ref: '#/components/schemas/PaginationInfo'

    PaginationInfo:
      type: object
      properties:
        currentPage:
          type: integer
          minimum: 1
        pageSize:
          type: integer
          minimum: 1
        totalItems:
          type: integer
          minimum: 0
        totalPages:
          type: integer
          minimum: 0
        hasNextPage:
          type: boolean
        hasPreviousPage:
          type: boolean

  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
              details:
                type: array
                items:
                  type: string

    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: Unauthorized

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: Resource not found

    ServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: Internal server error

security:
  - BearerAuth: []

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
